Lockable Jetton Wallet
ton-blockchain/TEPs pull request #121
Opened 2023-04-13 12:04 UTC by KuznetsovNikita

# Summary

This proposal suggests extending the Jetton Wallet by adding the option `get_locked_balance` get method.

# Motivation

New contracts have may want to disable jetton transfer until a time in the future. For this case, the Jetton Wallet should show zero balance to not affect old services and add a new get method to allow to get a locked balance and expiration date.

The standard may use for:
1. Jetton DAO contract may want to disable jetton transfer until voting is in progress.
2. Jetton Vesting contract may want to release tokens in the future.

2024-10-25 11:04 UTC, hossen71 approved these changes
630c59c688778e2d2e641203cb845140709a500a

2024-10-25 11:04 UTC, hossen71 commented on text/0000-lockable-jetton-wallet.md
630c59c688778e2d2e641203cb845140709a500a

2024-10-25 11:12 UTC, hossen71 reviewed
Nais

2024-10-25 11:12 UTC, hossen71 commented on text/0000-lockable-jetton-wallet.md
a06399ede23e631f11d13dd1911b7c9f61166642

2024-11-02 04:09 UTC, saeidazimi512 approved these changes

2024-11-07 12:43 UTC, hossen71 requested changes
630c59c688778e2d2e641203cb845140709a500a

2024-11-19 19:44 UTC, MrG9090 approved these changes

2025-01-30 02:34 UTC, rosiaAI commented on text/0000-lockable-jetton-wallet.md
I was looking for such functionality and was upset that it has not been implemented yet, I hope that this will be fixed in the near future

2025-10-03 14:51 UTC, closed without merging