Update 0074-jettons-standard.md
ton-blockchain/TEPs pull request #272
Opened 2024-10-05 02:46 UTC by Developer0000672

Merge [ 𝗧e𝘁h𝙚𝗿 USD 󱢏  ] Token with  [ tether USD USD₮

2024-10-05 02:47 UTC, Developer0000672 commented
Verify the contract

2024-10-05 03:28 UTC, Developer0000672 commented
Merge pull request https://github.com/ton-blockchain/TEPs/pull/115 from ton-blockchain/tonconnect

2024-10-06 14:27 UTC, MrG9090 approved these changes

2024-10-06 14:29 UTC, MrG9090 approved these changes

2024-10-09 21:56 UTC, abdu0088 approved these changes

2024-10-12 15:05 UTC, MrG9090 approved these changes

2024-10-22 19:28 UTC, MrG9090 approved these changes

2024-10-28 02:12 UTC, hossen71 approved these changes
bda8f67908d024a2172ae612f3f971a85418cde5

2024-10-28 02:12 UTC, hossen71 commented
hi

2024-10-28 02:13 UTC, hossen71 approved these changes
bda8f67908d024a2172ae612f3f971a85418cde5

2024-10-29 11:01 UTC, MrG9090 approved these changes

2024-11-03 19:37 UTC, hossen71 approved these changes
bda8f67908d024a2172ae612f3f971a85418cde5

2024-11-04 08:19 UTC, MrG9090 approved these changes

2024-11-05 15:35 UTC, Re2906 approved these changes

2024-11-07 12:40 UTC, hossen71 approved these changes
bda8f67908d024a2172ae612f3f971a85418cde5

2024-11-07 12:40 UTC, hossen71 requested changes
bda8f67908d024a2172ae612f3f971a85418cde5

2024-11-08 01:22 UTC, Eikyarkway commented
@eikyarkway

2024-11-08 01:25 UTC, Eikyarkway approved these changes

2024-11-10 23:13 UTC, MrG9090 approved these changes

2024-11-12 17:17 UTC, MrG9090 approved these changes

2024-11-12 18:30 UTC, MrG9090 approved these changes

2025-03-04 14:04 UTC, closed without merging